urls.py
from django.urls import path, include
from . import views 
from jpartyfb import urls

app_name = 'jpartyfb'  # This is where you define the namespace

urlpatterns = [
    path('', views.index, name='index'),
    path('play_football/', views.play_football, name='play_football'),
    path('manage_leagues/', views.manage_leagues, name='manage_leagues'),
    path('view_stats/', views.view_stats, name='view_stats'),
    
    #path('^show_league_form_1/(?P<source>\w+)/$', views.show_league_form_1, name='show_league_form_1'),
    path('show_league_form_1/<str:source>/', views.show_league_form_1, name='show_league_form_1'),
    
    path('start_new_season/', views.start_new_season, name='start_new_season'),
    path('edit_league_settings/', views.edit_league_settings, name='edit_league_settings'),
    
    #path('^process_create_league_form_1/(?P<edit_from_breadcrumb>\w+)/$', views.process_create_league_form_1, name='process_create_league_form_1'),
    path('process_create_league_form_1/<str:edit_from_breadcrumb>/', views.process_create_league_form_1, name='process_create_league_form_1'),
    
    
    path('process_create_league_form_final/', views.process_create_league_form_final, name='process_create_league_form_final'),
    path('choose_league/', views.choose_league, name='choose_league'),
    path('league_redirect/', views.league_redirect, name='league_redirect'),
    path('watch_draft/', views.watch_draft, name='watch_draft'),
    path('view_draft_list/', views.view_draft_list, name='view_draft_list'),
    path('start_new_season/', views.start_new_season, name='start_new_season'),
    path('draft_options/', views.draft_options, name='draft_options'),
    
    #path('^create_draft_list/(?P<source>\w+)$', views.create_draft_list, name='create_draft_list'),
    path('create_draft_list/<str:source>/', views.create_draft_list, name='create_draft_list'),
    
    path('watch_draft/', views.watch_draft, name='watch_draft'),
    path('view_draft_results/', views.view_draft_results, name='view_draft_results'),
    path('view_league_schedule/', views.view_league_schedule, name='view_league_schedule'),
    path('view_preseason_power_rankings/', views.view_preseason_power_rankings, name='view_preseason_power_rankings'),

]

forms.py
from django import forms
from django.forms.widgets import Input

#define tuples for select values
NUM_PLAYOFF_TEAMS = (
    ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')
)

NUM_WEEKS_REG_SEASON = (
    ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')
)

NUM_TEAMS_PER_CONFERENCE = (
    ('8', '8'), ('9', '9'), ('10', '10'), ('12', '12'), ('14', '14'), ('15', '15'), ('16', '16')
)

NUM_DIVISIONS_PER_CONFERENCE = (
    ('2', '2'), ('3', '3'), ('4', '4')
)

class CreateLeagueForm1(forms.Form):
    league_name = forms.CharField(label='League Name:', max_length=50)
    number_of_playoff_teams_select = forms.CharField(label='Number of Playoff Teams Per Conference', widget=forms.Select(choices=NUM_PLAYOFF_TEAMS))
    number_of_weeks_select = forms.CharField(label='Number of Weeks in Regular Season', widget=forms.Select(choices=NUM_WEEKS_REG_SEASON))
    number_of_teams_conf_select = forms.CharField(label='Number of Teams Per Conference', widget=forms.Select(choices=NUM_TEAMS_PER_CONFERENCE))
    number_of_divisions_select = forms.CharField(label='Number of Divisions Per Conference',
                                                     widget=forms.Select(choices=NUM_DIVISIONS_PER_CONFERENCE))

    

templates/jpartyfb/choose_league.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>


    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>
    <div style="height: 75px;"></div>

    <form name="choose_league_form" action="{% url 'jpartyfb:league_redirect' %}" method="post">
          <table>
             <tr>
                <td> Choose Your League:  </td>
                 <td> <select name="choose_league_select" id="choose_league_select">
                  {% for league in league_list %}

                      <option value="{{ league.0 }}"> {{ league.1 }} </option>

                  {% endfor %}
                  </select>
                  </td>
             </tr>
             <tr>
                 <td><div style="height: 20px;"></div></td>
             </tr>
             <tr>
                 <td align="center" colspan="2">
                     <input type='submit' name='choose_league_submit' id='choose_league_submit' />
                 </td>
             </tr>
          </table>

        <input type='hidden' name='source_page_hidden' id='source_page_hidden' value='{{ source_page }}' />

    </form>
    <div style="height: 75px;"></div>
</div>




{% endblock%}

templates/jpartyfb/create_new_league.html
{% extends "backendBase.html" %}

{% load staticfiles %}
{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
        <div class='breadcrumb' style='text-color: blue; background-color: white;'>
            <a href="{% url 'jpartyfb:index' %}">Home</a> >
            <a href="{% url 'jpartyfb:manage_leagues' %}">Manage Leagues</a> >
            <a href="{% url 'jpartyfb:create_new_league' %}">Create New League</a>
        </div>

{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>

    <div style="height: 75px;"></div>

    <form name="create_league_form_1" action="{% url 'jpartyfb:process_create_league_form_1' %}" method="post">
         <input type="checkbox" id="injury_checkbox" name="injury_checkbox" style="margin-left: -142px;" checked />
         <b>Toggle Injuries for League</b><br>
         <input type="checkbox" id="weather_checkbox" name="weather_checkbox" style="margin-left: -77px;" checked />
         <b>Toggle In Game Weather for League</b><br>
         <input type="checkbox" id="female_checkbox" name="female_checkbox" style="margin-left: -33px;" checked />
         <b>Toggle Allowing Female Players in League</b><br>

        <hr>
        <table cellpadding="5">
            {% for element in form %}
             <tr>
                 <td>
                    <label for="{{ element.name }}">{{ element.label }}</label>
                 </td>
                 <td>
                     {{ element }}
                 </td>
             </tr>
             {% endfor %}
              <tr><td><br></td></tr>
              <tr>
                  <td colspan="2" align="center">
                      <input type="button" id="submit_button" value='Choose Teams' />
                  </td>
              </tr>
          </table>
    </form>
</div>

<div style="height: 75px;"></div>

<script language="Javascript">

    $("#submit_button").click(function() {

        //check if the league name is not blank
        var league_name = $("#id_league_name").val()

        if (league_name == "") {
            alert("League must have a name")
            return
        }

        //check if the number of teams per conference is divisible by the number of divisions per conference
        //we need to make sure that all divisions have the same number of teams

        var num_teams_conference = $("#id_number_of_teams_conf_select").val()
        var num_divisions_conference = $("#id_number_of_divisions_select").val()

        if (num_teams_conference % num_divisions_conference != 0) {
            alert("Please choose numbers that allow for an equal number of teams per division in each conference")
            return
        }

        var the_form = document.forms[0];
        the_form.submit()

    })



</script>

{% endblock%}

templates/jpartyfb/draft_list.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
            <div class='breadcrumb' style='text-color: blue; background-color: white;'>
                <a href="{% url 'jpartyfb:index' %}">Home</a> >
                <a href="{% url 'jpartyfb:choose_league' %}">Choose League</a> >
                <a href="{% url 'jpartyfb:draft_options' %}">Draft Options</a>
            </div>

{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>

    <div style="height: 25px;"></div>

    <h3> Filter by Position</h3>

    <table align="center" border="1" width="35%">
        <tr align="center">
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=qb">QB</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=rb">RB</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=wr">WR</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=te">TE</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=fb">FB</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=ol">OL</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=dl">DL</a></td>
        </tr>
        <tr align="center">
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=lb">LB</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=cb">CB</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=sf">SF</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=k">K</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=p">P</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=sto">STO</a></td>
            <td width="5%"><a href="{% url 'jpartyfb:view_draft_list' %}?player_filter=std">STD</a></td>
        </tr>
        <tr align="center">
            <td colspan="7" width="35%"><a href="{% url 'jpartyfb:view_draft_list' %}">All</a></td>
        </tr>
    </table>

    <div style="height: 75px;"></div>

    <table width="100%" border="1">
	    <tr align="center">
            <td width="25%" style="background-color: #dddddd; font-weight: bold;">Name</td>
            <td width="10%" style="background-color: #dddddd; font-weight: bold;">Pos</td>
            <td width="25%" style="background-color: #dddddd; font-weight: bold;">Alma Mater</td>
            <td width="20%" style="background-color: #dddddd; font-weight: bold;">Height</td>
            <td width="20%" style="background-color: #dddddd; font-weight: bold;">Weight</td>
	    </tr>
        {% for this_player_list in player_info_lol %}
            <tr align="center" style="background-color: {% cycle '#ebfffe' '#99f2ec' %};">
                <td>{{ this_player_list.0 }}</td>
                <td>{{ this_player_list.1 }}</td>
                <td>{{ this_player_list.2 }}</td>
                <td>{{ this_player_list.3 }}</td>
                <td>{{ this_player_list.4 }}</td>
            </tr>
        {% endfor %}
	</table>

</div>
<div style="height: 75px;"></div>

{% endblock%}

templates/jpartyfb/draft_options.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
            <div class='breadcrumb' style='text-color: blue; background-color: white;'>
                <a href="{% url 'jpartyfb:index' %}">Home</a> >
                <a href="{% url 'jpartyfb:choose_league' %}">Choose League</a>
            </div>

{% if error_msg %}
    <p style="color: red;">
        {{ error_msg }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>
    <div style="height: 75px;"></div>

    <table width="100%">
	    <tr align="center">
	        
	        <td width="33%" align="center">
                <a href="{% url 'jpartyfb:create_draft_list' source='watch_draft' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/watch_draft.png' %}"/>
                    <img style="border-radius:1px;height:65px; width:260px;" src="{% static 'jpartyfb/images/text_graphics/watch_draft.png' %}"/>
                </a>
	        </td>
            <td width="33%" align="center">
                <a href="{% url 'jpartyfb:create_draft_list' source='fast_forward_draft' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/fast_forward_draft.png' %}"/>
                    <img style="border-radius:1px;height:65px; width:260px;" src="{% static 'jpartyfb/images/text_graphics/fast_forward_draft.png' %}"/>
                </a>
	        </td>
            <td width="33%" align="center">
                <a href="{% url 'jpartyfb:view_draft_list' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/view_draft_list.png' %}"/>
                    <img style="border-radius:1px;height:65px; width:260px;" src="{% static 'jpartyfb/images/text_graphics/view_draft_list.png' %}"/>
                </a>
	        </td>
	    </tr>
	</table>

</div>


{% endblock%}

templates/jpartyfb/draft_results.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}: {{ league_abbrev }} - Season {{ season_year }}</h1></div><br>
            <div class='breadcrumb' style='text-color: blue; background-color: white;'>
                <a href="{% url 'jpartyfb:index' %}">Home</a>
            </div>


{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>

    <table border="0" width="100%">
        <tr>
            <td align="left" width="15%">
                <b>Filter by Position:</b>
                <select id="position_filter_select" onchange="window.location.href='/jpartyfb/view_draft_results?position_filter=' + this.value">
                    {% for this_position in position_list %}
                        {% ifequal this_position position_filter %}
                            <option value="{{ this_position }}" SELECTED>{{ this_position }}</option>
                        {% else %}
                            <option value="{{ this_position }}">{{ this_position }}</option>
                        {% endifequal %}

                    {% endfor %}
                </select>
            </td>
            <td width="65%"></td>
            <td width="20%">
                <b>Filter by Team:</b>
                <select id="team_filter_select" onchange="window.location.href='/jpartyfb/view_draft_results?team_filter=' + this.value">
                    {% for this_team in team_list %}
                        {% if this_team == team_filter %}
                            <option value="{{ this_team }}" SELECTED>{{ this_team }}</option>
                        {% else %}
                            <option value="{{ this_team }}">{{ this_team }}</option>
                        {% endif %}

                    {% endfor %}
                </select>
            </td>
        </tr>
    </table>

    <div style="height: 25px;"></div>

    {% for round_number, player_info_lol in round_number_to_player_info_list_dict.items %}

        <h3>Round {{ round_number }}</h3>

        <table width="100%" border="1">
            <tr align="center">
                <td width="5%" style="background-color: #dddddd; font-weight: bold;">#</td>
                <td width="20%" style="background-color: #dddddd; font-weight: bold;">Name</td>
                <td width="15%" style="background-color: #dddddd; font-weight: bold;">Pos</td>
                <td width="15%" style="background-color: #dddddd; font-weight: bold;">Height</td>
                <td width="15%" style="background-color: #dddddd; font-weight: bold;">Weight</td>
                <td width="20%" style="background-color: #dddddd; font-weight: bold;">Team</td>
                <td width="10%" style="background-color: #dddddd; font-weight: bold;">Draft Rank</td>

            </tr>
            {% for this_player_list in player_info_lol %}
                <tr align="center" style="background-color: {% cycle '#ebfffe' '#99f2ec' %};">
                    <td>{{ this_player_list.0 }}</td>
                    <td>{{ this_player_list.1 }}</td>
                    <td>{{ this_player_list.2 }}</td>
                    <td>{{ this_player_list.3 }}</td>
                    <td>{{ this_player_list.4 }}</td>
                    <td>{{ this_player_list.5 }}</td>
                    <td>{{ this_player_list.6 }}</td>
                </tr>
            {% endfor %}
        </table>
        <div style="height: 25px;"></div>

    {% endfor %}

</div>
<div style="height: 75px;"></div>

{% endblock%}

templates/jpartyfb/manage_leagues.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
        <div class='breadcrumb' style='text-color: blue; background-color: white;'>
            <a href="{% url 'jpartyfb:index' %}">Home</a> >
            <a href="{% url 'jpartyfb:manage_leagues' %}">Manage Leagues</a>
        </div>

{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>
    <div style="height: 75px;"></div>

    <table width="100%">
	    <tr align="center">
	        
	        <td width="33%" align="center">
                <a href="{% url 'jpartyfb:show_league_form_1' source='cnl' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/create_new_league.png' %}"/>
                    <img style="border-radius:1px;height:43px; width:348px;" src="{% static 'jpartyfb/images/text_graphics/create_new_league.png' %}"/>
                </a>
	        </td>
            <td width="33%">
                <a href="{% url 'jpartyfb:start_new_season' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/start_new_season.png' %}"/>
                    <img style="border-radius:1px;height:37px; width:310px;" src="{% static 'jpartyfb/images/text_graphics/start_new_season.png' %}"/>
                </a>
	        </td>
            <td width="33%">
                <a href="{% url 'jpartyfb:edit_league_settings' %}">
                    <img style="border-radius:1px;height:108px; width:125px;" src="{% static 'jpartyfb/images/menu_icons/edit_league_settings.png' %}"/><br>
                    <img style="border-radius:1px;height:44px; width:354px;" src="{% static 'jpartyfb/images/text_graphics/edit_league_settings.png' %}"/>
                </a>
            </td>
	    </tr>
	</table>

</div>


{% endblock%}

templates/jpartyfb/show_league_form_1.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
        <div class='breadcrumb' style='text-color: blue; background-color: white;'>
            <a href="{% url 'jpartyfb:index' %}">Home</a> >
            <a href="{% url 'jpartyfb:manage_leagues' %}">Manage Leagues</a> >
            {% if source == 'els' %}
                <a href="{% url 'jpartyfb:show_league_form_1' source='els' %}">{{ source_page_title }}</a>
            {% else %}
                <a href="{% url 'jpartyfb:show_league_form_1' source='cnl' %}">{{ source_page_title }}</a>
            {% endif %}
        </div>

{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>
        </tr>
    </table>

    <div style="height: 75px;"></div>
    <form name="create_league_form_1" action="{% url 'jpartyfb:process_create_league_form_1' edit_from_breadcrumb='False' %}" method="post">

         {% if source == 'els' %}
             <input type="checkbox" id="injury_checkbox" name="injury_checkbox" style="margin-left: -142px;" {{ league_settings_dict.injury_setting }} />
         {% else %}
             <input type="checkbox" id="injury_checkbox" name="injury_checkbox" style="margin-left: -142px;" checked />
         {% endif %}

         <b>Toggle Injuries for League</b><br>

         {% if source == 'els' %}
             <input type="checkbox" id="weather_checkbox" name="weather_checkbox" style="margin-left: -77px;" {{ league_settings_dict.weather_setting }} />
         {% else %}
             <input type="checkbox" id="weather_checkbox" name="weather_checkbox" style="margin-left: -77px;" checked />
         {% endif %}

         <b>Toggle In Game Weather for League</b><br>

         {% if source == 'els' %}
             <input type="checkbox" id="female_checkbox" name="female_checkbox" style="margin-left: -33px;" {{ league_settings_dict.female_setting }} />
         {% else %}
             <input type="checkbox" id="female_checkbox" name="female_checkbox" style="margin-left: -33px;" checked />
         {% endif %}

         <b>Toggle Allowing Female Players in League</b><br>

         {% if source == 'els' %}
             <input type="checkbox" id="neutral_site_checkbox" name="neutral_site_checkbox" style="margin-left: -9px;" {{ league_settings_dict.neutral_site_setting }} />
         {% else %}
            <input type="checkbox" id="neutral_site_checkbox" name="neutral_site_checkbox" style="margin-left: -9px;" checked />
         {% endif %}

        <b>Toggle Using Neutral Site Stadiums in League</b><br>

        <hr>
        <table cellpadding="5">
            {% for element in form %}
             <tr>
                 <td>
                    <label for="{{ element.name }}">{{ element.label }}</label>
                 </td>
                 <td>
                     {{ element }}
                 </td>
             </tr>
             {% endfor %}
              <tr><td><br></td></tr>
             {% if source == 'els' %}
              <tr>
                <td colspan="2" align="center">
                    <input type="button" id="save_and_leave_button" class='submit_button' value='Save Settings and Go Home' style="width: 215px;" />
                </td>
              </tr>
             {% endif %}
             <tr><td><div style="height: 25px;"></div></td></tr>
              <tr>
                  <td colspan="2" align="center">
                      <input type="button" id="choose_teams_button" class='submit_button' value='Choose Teams' />
                  </td>
              </tr>
          </table>
         <input type="hidden" name="source_page_hidden" id="source_page_hidden" value="{{ source }}" />
         <input type="hidden" name="league_id_hidden" id="league_id_hidden" value="{{ league_id }}" />
         <input type="hidden" name="season_active_hidden" id="season_active_hidden" value="{{ season_active }}" />
         <input type="hidden" name="clicked_submit_button_hidden" id="clicked_submit_button_hidden" value="" />

    </form>
</div>

<div style="height: 75px;"></div>

<script language="Javascript">

    $(".submit_button").click(function() {

        var clicked_button_id = $(this).attr('id')

        if (clicked_button_id == "save_and_leave_button") {
            $("#clicked_submit_button_hidden").val("save_and_leave_button")
        } else {
            $("#clicked_submit_button_hidden").val("choose_teams_button")
        }

        //check if the league name is not blank
        var league_name = $("#id_league_name").val()

        if (league_name == "") {
            alert("League must have a name")
            return
        }

        //if the number of games per season is an odd number, and the neutral site stadium checkbox is not checked,
        //then alert the user
        var neutral_site_setting = $("#neutral_site_checkbox").prop('checked')
        var num_games_regular_season = $("#id_number_of_weeks_select").val()

        if (num_games_regular_season % 2 == 1 && neutral_site_setting == false) {
             alert("You must enable neutral site games when playing an odd number of regular season games")
             return
        }

        //if source page is els, then let user know that changing certain settings won't take effect
        //until the season is over. If user does not accept, then do not submit

        var source_page = $("#source_page_hidden").val()
        var season_active = $("#season_active_hidden").val()

        if (source_page == 'els' && season_active == 'False') {

            if (!confirm("Since you are making changes to settings in a league with an ongoing season, some settings will not take effect until the season is over")) {

                return

            }

        }

        if (clicked_button_id == "choose_teams_button") {

            //check if the number of teams per conference is divisible by the number of divisions per conference
            //we need to make sure that all divisions have the same number of teams

            var num_teams_conference = $("#id_number_of_teams_conf_select").val()
            var num_divisions_conference = $("#id_number_of_divisions_select").val()

            if (num_teams_conference % num_divisions_conference != 0) {
                alert("Please choose numbers that allow for an equal number of teams per division in each conference")
                return
            }

        }//end if

        var the_form = document.forms[0];
        the_form.submit()

    })



</script>

{% endblock%}

templates/jpartyfb/view_stats.html
{% extends "backendBase.html" %}

{% load static %}

{%block mainContent%}	
	<div class="container" style="border:1px solid #C0C0C0;" align="center">
          {% csrf_token %}
		<div class='row' style='text-align:center;'>
            <div style="float:left;">
			</div>
			<h1>{{ welcome_message }}</h1></div><br>
        <div class='breadcrumb' style='text-color: blue; background-color: white;'>
            <a href="{% url 'jpartyfb:index' %}">Home</a> >
            <a href="{% url 'jpartyfb:view_stats' %}">View Stats</a>
        </div>

{% if Error_message %}
    <p style="color: red;">
        {{ Error_message }}
    </p>
{% endif %}

    <table align="center">
        <tr>
            <!--<img style="border-radius:1px;height:160px; width:160px;" src="{% static 'jpartyfb/images/league_logo.png' %}"/>-->
        </tr>
    </table>
    <div style="height: 75px;"></div>

    <table width="100%">
	    <tr align="center">
	        
	        <td width="33%" align="center">
                <a href="{% url 'jpartyfb:index' %}">
                    <img style="border-radius:1px;height:143px; width:156px;" src="{% static 'jpartyfb/images/football.png' %}"/>
                    <img style="border-radius:1px;height:45px; width:227px;" src="{% static 'jpartyfb/images/text_graphics/play_football.png' %}"/>
                </a>
	        </td>
            <td width="33%">
                <img style="border-radius:1px;height:143px; width:156px;" src="{% static 'jpartyfb/images/football.png' %}"/>
                <img style="border-radius:1px;height:41px; width:300px;" src="{% static 'jpartyfb/images/text_graphics/manage_leagues.png' %}"/>
	        </td>
            <td width="33%">
                <img style="border-radius:1px;height:143px; width:156px;" src="{% static 'jpartyfb/images/football.png' %}"/><br>
                <img style="border-radius:1px;height:37px; width:189px;" src="{% static 'jpartyfb/images/text_graphics/view_stats.png' %}"/>
	        </td>
	    </tr>
	</table>

</div>


{% endblock%}